# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check license header

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '22'
    - name: Build with Maven
      run: xvfb-run mvn -B license:check
